# Exercise definitions with their properties
exercises = {
    "15-Degree Incline Bench Press": {
        "primary": ["Chest", "Triceps", "Front Delts"],
        "isometric": ["Lower Back"],
        "is_leg": False,
        "is_compound": True,
    },
    "Front Raise": {
        "primary": ["Front Delts"],
        "isometric": ["Biceps"],
        "is_leg": False,
        "is_compound": False,
    },
    "Lateral Raise": {
        "primary": ["Lateral Delts"],
        "isometric": [],
        "is_leg": False,
        "is_compound": False,
    },
    "Leg Extension": {
        "primary": ["Quads", "Rectus Femoris"],
        "isometric": [],
        "is_leg": True,
        "is_compound": False,
    },
    "Cable Curl": {
        "primary": ["Biceps"],
        "isometric": [],
        "is_leg": False,
        "is_compound": False,
    },
    "Pulldown": {
        "primary": ["Lats", "Biceps"],
        "secondary": ["Lower Traps", "Rear Delts"],
        "isometric": [],
        "is_leg": False,
        "is_compound": True,
    },
    "Squat": {
        "primary": ["Quads", "Glutes"],
        "secondary": ["Hamstrings", "Lower Back"],
        "isometric": ["Lower Back"],
        "is_leg": True,
        "is_compound": True,
    },
    "Rear Delts": {
        "primary": ["Rear Delts"],
        "isometric": [],
        "is_leg": False,
        "is_compound": False,
    },
    "Shrugs": {
        "primary": ["Upper Traps"],
        "isometric": [],
        "is_leg": False,
        "is_compound": False,
    },
    "Kelso Shrugs": {
        "primary": ["Mid Traps"],
        "isometric": [],
        "is_leg": False,
        "is_compound": False,
    },
    "Chest Fly": {
        "primary": ["Chest"],
        "secondary": ["Front Delts"],
        "isometric": [],
        "is_leg": False,
        "is_compound": False,
    },
    "Upper Back Rows": {
        "primary": ["Mid Traps", "Rear Delts"],
        "secondary": ["Lats", "Biceps"],
        "isometric": ["Lower Back"],
        "is_leg": False,
        "is_compound": True,
    },
    "Triceps Extension": {
        "primary": ["Triceps", "Long Head"],
        "isometric": [],
        "is_leg": False,
        "is_compound": False,
    },
    "Leg Curl": {
        "primary": ["Hamstrings", "Short Head"],
        "isometric": [],
        "is_leg": True,
        "is_compound": False,
    },
    "Stiff-Legged Deadlift": {
        "primary": ["Hamstrings", "Glutes"],
        "secondary": ["Lower Back"],
        "isometric": ["Lower Back", "Upper Traps"],
        "is_leg": True,
        "is_compound": True,
    },
    "Lat Prayer": {
        "primary": ["Lats", "Long Head"],
        "isometric": [],
        "is_leg": False,
        "is_compound": False,
    },
}

# Define MAV targets
mav_targets = {
    "Chest": 12,
    "Triceps": 10,
    "Long Head": 10,
    "Front Delts": 8,
    "Lateral Delts": 12,
    "Rear Delts": 12,
    "Lats": 14,
    "Mid Traps": 8,
    "Upper Traps": 8,
    "Lower Traps": 14,
    "Biceps": 14,
    "Quads": 12,
    "Rectus Femoris": 12,
    "Hamstrings": 10,
    "Short Head": 10,
    "Glutes": 8,  # Report only, do not optimize
    "Lower Back": 14,  # Report only, do not optimize
}

# Compatibility matrix
compatibility_matrix = {
    ("Bench Press", "Chest Fly"): 0,
    ("Bench Press", "Front Raise"): 0,
    ("Bench Press", "Lateral Raise"): 0,
    ("Bench Press", "Triceps Extension"): 0,
    ("Bench Press", "Squat"): 0,
    ("Bench Press", "Leg Curl"): 1,
    ("Bench Press", "Leg Extension"): 0,
    ("Bench Press", "Shrugs"): 0,
    ("Bench Press", "Upper Back Rows"): 0,
    ("Bench Press", "Kelso Shrugs"): 0,
    ("Bench Press", "Rear Delts"): 0,
    ("Bench Press", "Cable Curl"): 0,
    ("Bench Press", "Stiff-Legged Deadlift"): 0,
    ("Bench Press", "Pulldown"): 0,
    ("Bench Press", "Lat Prayer"): 0,
    ("Chest Fly", "Front Raise"): 0,
    ("Chest Fly", "Lateral Raise"): 0,
    ("Chest Fly", "Triceps Extension"): 0,
    ("Chest Fly", "Squat"): 1,
    ("Chest Fly", "Leg Curl"): 1,
    ("Chest Fly", "Leg Extension"): 0,
    ("Chest Fly", "Shrugs"): 0,
    ("Chest Fly", "Upper Back Rows"): 1,
    ("Chest Fly", "Kelso Shrugs"): 1,
    ("Chest Fly", "Rear Delts"): 0,
    ("Chest Fly", "Cable Curl"): 0,
    ("Chest Fly", "Stiff-Legged Deadlift"): 0,
    ("Chest Fly", "Pulldown"): 1,
    ("Chest Fly", "Lat Prayer"): 1,
    ("Front Raise", "Lateral Raise"): 1,
    ("Front Raise", "Triceps Extension"): 1,
    ("Front Raise", "Squat"): 1,
    ("Front Raise", "Leg Curl"): 1,
    ("Front Raise", "Leg Extension"): 1,
    ("Front Raise", "Shrugs"): 0,
    ("Front Raise", "Upper Back Rows"): 1,
    ("Front Raise", "Kelso Shrugs"): 1,
    ("Front Raise", "Rear Delts"): 1,
    ("Front Raise", "Cable Curl"): 1,
    ("Front Raise", "Stiff-Legged Deadlift"): 0,
    ("Front Raise", "Pulldown"): 1,
    ("Front Raise", "Lat Prayer"): 1,
    ("Lateral Raise", "Triceps Extension"): 1,
    ("Lateral Raise", "Squat"): 1,
    ("Lateral Raise", "Leg Curl"): 1,
    ("Lateral Raise", "Leg Extension"): 1,
    ("Lateral Raise", "Shrugs"): 0,
    ("Lateral Raise", "Upper Back Rows"): 1,
    ("Lateral Raise", "Kelso Shrugs"): 1,
    ("Lateral Raise", "Rear Delts"): 1,
    ("Lateral Raise", "Cable Curl"): 1,
    ("Lateral Raise", "Stiff-Legged Deadlift"): 0,
    ("Lateral Raise", "Pulldown"): 1,
    ("Lateral Raise", "Lat Prayer"): 1,
    ("Triceps Extension", "Squat"): 1,
    ("Triceps Extension", "Leg Curl"): 1,
    ("Triceps Extension", "Leg Extension"): 1,
    ("Triceps Extension", "Shrugs"): 0,
    ("Triceps Extension", "Upper Back Rows"): 1,
    ("Triceps Extension", "Kelso Shrugs"): 1,
    ("Triceps Extension", "Rear Delts"): 1,
    ("Triceps Extension", "Cable Curl"): 0,
    ("Triceps Extension", "Stiff-Legged Deadlift"): 1,
    ("Triceps Extension", "Pulldown"): 1,
    ("Triceps Extension", "Lat Prayer"): 1,
    ("Squat", "Leg Curl"): 1,
    ("Squat", "Leg Extension"): 1,
    ("Squat", "Shrugs"): 1,
    ("Squat", "Upper Back Rows"): 0,
    ("Squat", "Kelso Shrugs"): 0,
    ("Squat", "Rear Delts"): 1,
    ("Squat", "Cable Curl"): 1,
    ("Squat", "Stiff-Legged Deadlift"): 1,
    ("Squat", "Pulldown"): 0,
    ("Squat", "Lat Prayer"): 1,
    ("Leg Curl", "Leg Extension"): 0,
    ("Leg Curl", "Shrugs"): 1,
    ("Leg Curl", "Upper Back Rows"): 1,
    ("Leg Curl", "Kelso Shrugs"): 1,
    ("Leg Curl", "Rear Delts"): 1,
    ("Leg Curl", "Cable Curl"): 1,
    ("Leg Curl", "Stiff-Legged Deadlift"): 1,
    ("Leg Curl", "Pulldown"): 0,
    ("Leg Curl", "Lat Prayer"): 1,
    ("Leg Extension", "Shrugs"): 1,
    ("Leg Extension", "Upper Back Rows"): 1,
    ("Leg Extension", "Kelso Shrugs"): 0,
    ("Leg Extension", "Rear Delts"): 1,
    ("Leg Extension", "Cable Curl"): 0,
    ("Leg Extension", "Stiff-Legged Deadlift"): 0,
    ("Leg Extension", "Pulldown"): 1,
    ("Leg Extension", "Lat Prayer"): 1,
    ("Shrugs", "Upper Back Rows"): 1,
    ("Shrugs", "Kelso Shrugs"): 1,
    ("Shrugs", "Rear Delts"): 0,
    ("Shrugs", "Cable Curl"): 0,
    ("Shrugs", "Stiff-Legged Deadlift"): 1,
    ("Shrugs", "Pulldown"): 1,
    ("Shrugs", "Lat Prayer"): 1,
    ("Upper Back Rows", "Kelso Shrugs"): 1,
    ("Upper Back Rows", "Rear Delts"): 1,
    ("Upper Back Rows", "Cable Curl"): 1,
    ("Upper Back Rows", "Stiff-Legged Deadlift"): 1,
    ("Upper Back Rows", "Pulldown"): 0,
    ("Upper Back Rows", "Lat Prayer"): 1,
    ("Kelso Shrugs", "Rear Delts"): 1,
    ("Kelso Shrugs", "Cable Curl"): 0,
    ("Kelso Shrugs", "Stiff-Legged Deadlift"): 0,
    ("Kelso Shrugs", "Pulldown"): 1,
    ("Kelso Shrugs", "Lat Prayer"): 1,
    ("Rear Delts", "Cable Curl"): 0,
    ("Rear Delts", "Stiff-Legged Deadlift"): 1,
    ("Rear Delts", "Pulldown"): 1,
    ("Rear Delts", "Lat Prayer"): 1,
    ("Cable Curl", "Stiff-Legged Deadlift"): 0,
    ("Cable Curl", "Pulldown"): 1,
    ("Cable Curl", "Lat Prayer"): 1,
    ("Stiff-Legged Deadlift", "Pulldown"): 1,
    ("Stiff-Legged Deadlift", "Lat Prayer"): 1,
    ("Pulldown", "Lat Prayer"): 1,
}
